name: lab_exam
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.10.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Thư viện Riverpod
  riverpod_annotation: ^2.3.5
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # Các công cụ tạo code tự động
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  custom_lint: ^0.6.4

flutter:
  uses-material-design: true

  # Khai báo thư mục chứa ảnh
  assets:
    - assets/images/
